CREATE DATABASE QL_GIAOHANG
GO

USE QL_GIAOHANG
GO

CREATE TABLE KHACHHANG(
MAKHACHHANG INT NOT NULL,
TENCONGTY NVARCHAR(50) NOT NULL,
TENGIAODICH VARCHAR(20) NOT NULL,
DIACHI NVARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
DIENTHOAI VARCHAR(20) NOT NULL,
FAX VARCHAR(50),
CONSTRAINT PK_MAKHACHHANG PRIMARY KEY (MAKHACHHANG)
)
GO

CREATE TABLE DONDATHANG(
SOHOADON INT NOT NULL,
MAKHACHHANG INT,
MANHANVIEN INT NOT NULL,
NGAYDATHANG DATE NOT NULL,
NGAYGIAOHANG DATE NOT NULL,
NGAYCHUYENHANG DATE ,
NOIGIAOHANG VARCHAR(100),
CONSTRAINT PK_SOHOADON PRIMARY KEY (SOHOADON),
CONSTRAINT FK_MAKHACHHANG FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG),
CONSTRAINT FK_MANHANVIEN FOREIGN KEY (MANHANVIEN) REFERENCES NHANVIEN(MANHANVIEN)
)

CREATE TABLE NHANVIEN(
MANHANVIEN INT NOT NULL,
HO NVARCHAR(20) NOT NULL,
TEN NVARCHAR(10) NOT NULL,
NGAYSINH DATE NOT NULL,
NGAYLAMVIEC DATE NOT NULL,
DIACHI NVARCHAR(50) NOT NULL,
DIENTHOAI VARCHAR(20) NOT NULL,
LUONGCOBAN FLOAT NOT NULL,
PHUCAP FLOAT,
CONSTRAINT PK_MANHANVIEN PRIMARY KEY (MANHANVIEN),
)
GO

CREATE TABLE NHACUNGCAP(
MACONGTY INT NOT NULL,
TENCONGTY NVARCHAR(50) NOT NULL,
TENGIAODICH VARCHAR(20) NOT NULL,
DIACHI NVARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
DIENTHOAI VARCHAR(20) NOT NULL,
FAX VARCHAR(50),
CONSTRAINT PK_MACONGTY PRIMARY KEY (MACONGTY),
)
GO

CREATE TABLE MATHANG(
MAHANG INT NOT NULL,
TENHANG NVARCHAR(50) NOT NULL,
MACONGTY INT,
MALOAIHANG INT,
SOLUONG INT NOT NULL,
DONVITINH NVARCHAR(10) NOT NULL,
GIAHANG FLOAT NOT NULL,
CONSTRAINT PK_MAHANG PRIMARY KEY (MAHANG),
CONSTRAINT FK_MACONGTY FOREIGN KEY (MACONGTY) REFERENCES NHACUNGCAP(MACONGTY),
CONSTRAINT FK_MALOAIHANG FOREIGN KEY (MALOAIHANG)REFERENCES LOAIHANG(MALOAIHANG)
)
GO

CREATE TABLE CHITIETDATHANG(
SOHOADON INT,
MAHANG INT,
GIABAN FLOAT NOT NULL,
SOLUONG INT NOT NULL,
MUCGIAMGIA FLOAT,
CONSTRAINT FK_SOHOADON FOREIGN KEY (SOHOADON) REFERENCES DONDATHANG(SOHOADON),
CONSTRAINT FK_MAHANG FOREIGN KEY(MAHANG) REFERENCES MATHANG(MAHANG)
)
GO

CREATE TABLE LOAIHANG(
MALOAIHANG INT NOT NULL,
TENLOAIHANG NVARCHAR(20) NOT NULL
CONSTRAINT PK_MALOAIHANG PRIMARY KEY (MALOAIHANG),
)
GO


