// <auto-generated />
using MedicalDeclaration.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MedicalDeclaration.Migrations
{
    [DbContext(typeof(MedicalDeclarationDb))]
    [Migration("20200911075236_CreateDiseaseSymptomsAndExposureHistoryTable")]
    partial class CreateDiseaseSymptomsAndExposureHistoryTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-preview.8.20407.4");

            modelBuilder.Entity("MedicalDeclaration.Models.Entity.DiseaseSymptomsAndExposureHistory.DiseaseSymptomsAndExposureHistory", b =>
                {
                    b.Property<int>("DSAEH_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("AnimalContact")
                        .HasColumnType("bit");

                    b.Property<bool>("BleedingFromTheSkin")
                        .HasColumnType("bit");

                    b.Property<bool>("CloseContact")
                        .HasColumnType("bit");

                    b.Property<bool>("Cough")
                        .HasColumnType("bit");

                    b.Property<bool>("Diarrhea")
                        .HasColumnType("bit");

                    b.Property<bool>("Fever")
                        .HasColumnType("bit");

                    b.Property<bool>("SkinRash")
                        .HasColumnType("bit");

                    b.Property<bool>("SoreThroat")
                        .HasColumnType("bit");

                    b.Property<bool>("Sultry")
                        .HasColumnType("bit");

                    b.Property<string>("VaccinesOrBiologicalsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VomitingOrNausea")
                        .HasColumnType("bit");

                    b.HasKey("DSAEH_Id");

                    b.ToTable("DiseaseSymptomsAndExposureHistorys");
                });

            modelBuilder.Entity("MedicalDeclaration.Models.Entity.InfomationVehicle", b =>
                {
                    b.Property<int>("TravelInformationId")
                        .HasColumnType("int");

                    b.Property<int>("VehiclesId")
                        .HasColumnType("int");

                    b.HasKey("TravelInformationId", "VehiclesId");

                    b.ToTable("InfomationVehicles");
                });

            modelBuilder.Entity("MedicalDeclaration.Models.Entity.VietNamDb.ContactAddress", b =>
                {
                    b.Property<int>("ContactAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("ContactAddressId");

                    b.ToTable("ContactAdds");
                });
#pragma warning restore 612, 618
        }
    }
}
