CREATE DATABASE QL_ThuVien
GO

USE QL_ThuVien
GO

CREATE TABLE Student(
StudentID INT NOT NULL,
StudentName NVARCHAR(30) NOT NULL,
DateOfBirth DATE NOT NULL,
Adress NVARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
Phone VARCHAR(20) NOT NULL
CONSTRAINT PK_StudentID PRIMARY KEY (StudentID)
)
GO

CREATE TABLE Book(
BookID INT NOT NULL,
BookName NVARCHAR(50) NOT NULL,
CategoryID INT NOT NULL,
Author NVARCHAR(30) NOT NULL
CONSTRAINT PK_BookID PRIMARY KEY (BookID)
CONSTRAINT FK_CategoryID FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID),
)
GO

CREATE TABLE Categories(
CategoryID INT NOT NULL,
CategoryName NVARCHAR(30) NOT NULL
CONSTRAINT PK_CategoryID PRIMARY KEY (CategoryID)
)
GO

CREATE TABLE BorrowOrderBook(
BookID INT NOT NULL,
StudentID INT NOT NULL,
DateBorrow DATE NOT NULL,
DatePay DATE,
CreatorBorrow NVARCHAR(30) NOT NULL
CONSTRAINT PK_BorrowOrderBook PRIMARY KEY (BookID,StudentID)
CONSTRAINT FK_BookID FOREIGN KEY (BookID) REFERENCES Book(BookID),
CONSTRAINT FK_StudentID FOREIGN KEY (StudentID) REFERENCES Student(StudentID),
)
GO