CREATE DATABASE BT_S3
GO

USE BT_S3
GO

CREATE TABLE HOCVIEN
(
ID INT NOT NULL,
TEN NVARCHAR(30) NOT NULL,
TUOI INT NOT NULL,
KHOAHOC NVARCHAR(15) NOT NULL,
SOTIEN FLOAT NOT NULL
)

INSERT INTO HOCVIEN (ID, TEN, TUOI, KHOAHOC, SOTIEN)
VALUES (1, N'Hoàng', 21, 'CNTT', 400000);

INSERT INTO HOCVIEN (ID, TEN, TUOI, KHOAHOC, SOTIEN)
VALUES (2, N'Việt', 19, 'DTVT', 320000);

INSERT INTO HOCVIEN (ID, TEN, TUOI, KHOAHOC, SOTIEN)
VALUES (3, N'Thành', 18, 'KTDN', 400000);

INSERT INTO HOCVIEN (ID, TEN, TUOI, KHOAHOC, SOTIEN)
VALUES (4, N'Nhân', 19, 'CK', 450000);

INSERT INTO HOCVIEN (ID, TEN, TUOI, KHOAHOC, SOTIEN)
VALUES (5, N'Hương', 20, 'TCNH', 500000);

INSERT INTO HOCVIEN (ID, TEN, TUOI, KHOAHOC, SOTIEN)
VALUES (5, N'Hương', 20, 'TCNH', 200000);

SELECT * FROM HOCVIEN
DROP TABLE HOCVIEN

-- Viết câu lệnh hiện thị tất cả các dòng có tên là Huong
SELECT * 
FROM HOCVIEN AS H
WHERE H.TEN = N'Hương'
GO

-- Viết câu lệnh lấy ra tổng số tiền của Huong
SELECT	H.TEN AS 'Tên',
		SUM(H.SOTIEN) AS 'Tổng tiền'
FROM HOCVIEN AS H
WHERE H.TEN = N'Hương'
GROUP BY H.TEN
GO

-- Viết câu lệnh lấy ra tên danh sách của tất cả học viên, không trùng lặp
SELECT DISTINCT		H.ID AS 'ID',
					H.TEN AS 'Tên'
FROM HOCVIEN AS H
GO
